# Generated by Django 2.2 on 2020-08-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgm', '0003_auto_20200819_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
