# Generated by Django 2.2 on 2020-08-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgm', '0004_delete_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_business', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_email', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
