# Generated by Django 2.2 on 2020-08-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgm', '0005_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='due_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
