# Generated by Django 2.2 on 2020-08-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgm', '0006_supplier_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
