# Generated by Django 2.2 on 2020-08-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgm', '0009_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
